// Include Directories
+incdir+/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/inc
+incdir+/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common
+incdir+/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design
+incdir+/fact_data/shiruizhao/coralnpu/hdl/verilog

// Defines
+define+USE_GENERIC
+define+TB_SUPPORT
+define+VLEN_128
+define+ZVE32F_ON

// Hand-written RTL Design Files
/fact_data/shiruizhao/coralnpu/hdl/verilog/ClockGate.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/EMLUnit.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/RstSync.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/adder.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/arb_round_robin.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/barrel_shifter.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/cdffr.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/compressor_3_2.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/compressor_4_2.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/dff.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/edff_2d.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/edff.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/fifo_flopped_2w2r.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/fifo_flopped_4w2r.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/fifo_flopped.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/handshake_ff.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/handshake_multi_fifo.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/multi_fifo.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/openFifo4_flopped_ptr.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/common/openFifo8_flopped_2w2r.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/Aligner.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/EMLUnit.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/MultiFifo.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_alu.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_alu_unit_addsub.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_alu_unit_eml.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_alu_unit_execution_p1.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_alu_unit_mask.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_alu_unit_mask_viota.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_alu_unit_other.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_alu_unit_shift.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_alu_unit.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_arb.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_decode_ctrl.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_decode_de2.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_decode.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_decode_unit_ari_de2.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_decode_unit_ari.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_decode_unit_de2.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_decode_unit_lsu_de2.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_decode_unit_lsu.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_decode_unit.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_dispatch_bypass.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_dispatch_ctrl.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_dispatch_operand.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_dispatch_opr_byte_type.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_dispatch_raw_uop_rob.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_dispatch_raw_uop_uop.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_dispatch_structure_hazard.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_dispatch.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_div.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_div_unit_divider.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_div_unit.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_fdiv_wrapper.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_fma.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_fma_wrapper.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_freduction.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_lsu_remap.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_mac_unit.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_mulmac.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_mul_unit_mul8.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_mul_unit.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_pmtrdt.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_pmtrdt_unit_permutation.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_pmtrdt_unit_reduction_alu.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_pmtrdt_unit_reduction.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_pmtrdt_unit.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_retire.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_retire_waw.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_rob.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_sqrt7_rec7.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_vrf_reg.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/rvv_backend_vrf.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/RvvCore.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/design/RvvFrontEnd.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/rvv_vrf_reg.sv
/fact_data/shiruizhao/coralnpu/hdl/verilog/Sram_1rw_256x256.v
/fact_data/shiruizhao/coralnpu/hdl/verilog/Sram_1rwm_256x288.v
/fact_data/shiruizhao/coralnpu/hdl/verilog/Sram.v

// Include Header Files
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/inc/rvv_backend_alu.svh
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/inc/rvv_backend_config.svh
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/inc/rvv_backend_define.svh
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/inc/rvv_backend_dispatch.svh
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/inc/rvv_backend_div.svh
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/inc/rvv_backend_fma.svh
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/inc/rvv_backend_pmtrdt.svh
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/inc/rvv_backend_sva.svh
/fact_data/shiruizhao/coralnpu/hdl/verilog/rvv/inc/rvv_backend.svh

// Generated Chisel Verilog Files
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/Alu.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/CoreMiniAxi.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/CoreMiniHighmemAxi.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/CoreMini_ITCM512KB_DTCM512KBAxi.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/CoreMini.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/CoreMiniVerificationAxi.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/CoreScalar.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/Core.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/DBus2AxiV2.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/Dvu.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/L1DCacheBank.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/L1DCache.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/L1ICache.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/Mlu.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/RvvCoreMiniAxi.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/RvvCoreMiniHighmemAxi.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/RvvCoreMini_ITCM512KB_DTCM512KBAxi.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/RvvCoreMiniTlul.sv
/fact_data/shiruizhao/coralnpu/bazel-bin/hdl/chisel/src/coralnpu/RvvCoreMiniVerificationAxi.sv

// DPI / SRAM Backdoor Files
/fact_data/shiruizhao/coralnpu/hdl/verilog/sram_backdoor.cc
